version: "2.0"
services:
  pg:
    image: postgres:latest
    container_name: pgrs 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 25s 
    volumes:
      - ./deployments/sql:/docker-entrypoint-initdb.d  
  rs:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1   
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --pass 29102087 ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5   
    volumes:
      - ./deployments/redis/init.sh:/init.sh
    entrypoint: bash -c "/init.sh"
  bruteforce:
    build:
      context: ./
      dockerfile: ./building/.dockerfile
    container_name: bruteforce
    depends_on:
      pg:     
        condition: service_healthy 
      rs:     
        condition: service_healthy       
    ports:
      - 8081:8081
      - 5051:5051

     
