version: "1.0"
services:
  pg:
    image: postgres:latest
    container_name: pgrs 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 25s 
    volumes:
    - ./deployments/sql:/docker-entrypoint-initdb.d   
  bruteforce:
    build:
      context: .
      dockerfile: build/.dockerfile
    container_name: bruteforce
    depends_on:
      pg:     
        condition: service_healthy 
    ports:
      - 8081:8081

     
