expire-limit = 60
tick-interval = 500
expire-base = "in_redis"

[bruteforce-limits]
try-for-login = 10
try-for-pass = 100
try-for-ip = 1000

[logger]
level = "INFO"
log_encoding = "console"

[database]
connect_str = "postgres://ids79:ids79@pg:5432/bruteforce"

[http-server]
address = "0.0.0.0:8081"

[grpc-server]
address = "0.0.0.0:5051"

[redis]
address = "rs:6379"
pass = "29102087"