name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ./

      - name: make build
        run: make build
        working-directory: ./

      - name: make test
        run: make test
        working-directory: ./