name: Makefile CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout code
      uses: actions/checkout@v3

    - name: run linter
      run: make lint

    - name: run test
      run: make test

    - name: building
      run: make build
